# Site wide configuration

title:            Keepcosmos
locale:           ko_KR
url:


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6


# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: 신재현
  avatar: profile-image.jpg
  bio: |
    저는 ...<a href='/about' style='color: #0288D1'>더보기</a>
  email: keepcosmos@gmail.com
  disqus-shortname: keepcosmos
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    universal-analytics: UA-72801021-1
    verify: Aw0AEPpyMWNhqsjBfYQWEXD76_tYYamQxaRFJiH5KK0
    ad-client:
    ad-slot:
  bing-verify:
  github: keepcosmos
  stackoverflow: 1306187/jaehyun-shin
  linkedin: jaehyun-shin-22429640
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
